language: objective-c
before_script: 
  - gem install xcpretty
script:
  - xcodebuild -workspace "Example/HoodieExample.xcworkspace" -scheme HoodieExample -destination platform='iOS Simulator',OS=7.1,name='iPhone Retina (4-inch)' clean test -sdk iphonesimulator | xcpretty -c -t
